# expluded words

excluded_words <- tribble(~excluded,
                         "poubelle",
                         "tiroiren",
                         "darf",
                         "daref",
                         "dwaref",
                         "meinden",
                         "uandoen",
                         "mondigmoien",
                         "g",
                         "t",
                         "dwaref",
                         "muar",
                         "muer",
                         "hanri",
                         "päiperlek",
                         "nait",
                         "riäd"
                         )

# allowed_formants <- tribble(~label, ~allowedMaxF1, ~allowedMaxF2,
#                             "iː", 500, 3000,
#                             "i", 500, 3000,
#                             "eː", 600, 2800,
#                             "e", 600, 2800,
#                             "ə", 800, 2000,
#                             "ɜɪ", 700, 2500,
#                             "ɑ", 800, 1600,
#                             "ɑɪ", 900, 1600,
#                             "ɑʊ", 600, 1600,
#                             "aː", 1100, 1600,
#                             "æ", 1100, 2000,
#                             "æːɪ", 1100, 2000,
#                             "æːʊ", 1100, 2000,
#                             "o", 700, 1400,
#                             "ɔ", 800, 1400,
#                             "oː", 700, 1400,
#                             "u", 500, 1100,
#                             "əʊ", 700, 1600,
#                             "iə", 500, 3000,
#                             "uə", 500, 1100)